# curl --location --request POST 'http://localhost:8080/novo'
#--header 'Content-Type: text/plain'
#--data-raw '{
#  "id": 999,
#  "value": "content"
#}'
POST http://localhost:8080/novo
Content-Type: text/plain

{
  "id": 999,
  "value": "content"
}

###


###

GET http://localhost:8080
Accept: application/json

###
POST http://localhost:8080/novo
Content-Type: application/json
{
    "id": 2,
    "name": null
}





